[[tool.uv.index]]
url = "https://pypi.ci.artifacts.walmart.com/artifactory/api/pypi/pythonhosted-pypi-release-remote/simple/"
default = true

[project]
name = "langchain-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=26.3.1",
    "certifi>=2026.4.22",
    "isort>=8.0.1",
    "langchain>=1.2.18",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.1",
    "langchain-openai>=1.2.1",
    "langchain-pinecone>=0.2.0",
    "langchain-tavily>=0.2.18",
    "langchain-text-splitters>=0.3.0",
    "pandas>=3.0.3",
    "python-dotenv>=1.2.2",
    "rich>=15.0.0",
    "streamlit>=1.57.0",
    "tavily-python>=0.7.24",
]
